# Walkthrough 05: Structured Data Transformation - Production Error Handling

input:
  stdin:
    codec: lines

pipeline:
  processors:
    - mapping: |
        # Multiple fallback chains
        root.user_id = this.user.id catch this.userId catch this.user_identifier catch "unknown"

        # Type conversions with defaults
        root.count = this.count.number() catch 0
        root.amount = this.amount.number() catch 0.0
        root.enabled = this.enabled.bool() catch true
        root.priority = this.priority.number() catch 5

        # Safe array access
        root.first_tag = (this.tags catch []).index(0) catch "untagged"
        root.tags_array = this.tags catch []

        # Null-safe nested access
        root.city = this.user.address.city catch ""
        root.country = this.user.address.country catch "US"

        # Preserve valid data
        root.event_type = this.type catch "unknown"
        root.timestamp = this.timestamp catch now().ts_format("2006-01-02T15:04:05Z")

output:
  stdout:
    codec: lines
